export const TENQUANCO = {
    TRONG: '',
    TUONG: 'Tướng',
    SI_TRAI: 'Sĩ Trái',
    SI_PHAI: 'Sĩ Phải',
    BO_TRAI: 'Bồ Trái',
    BO_PHAI: 'Bồ Phải',
    NGUA_TRAI: 'Ngựa Trái',
    NGUA_PHAI: 'Ngựa Phải',
    XE_TRAI: 'Xe Trái',
    XE_PHAI: 'Xe Phải',
    PHAO_TRAI: 'Pháo Trái',
    PHAO_PHAI: 'Pháo Phải',
    CHOT_MOT: 'Chốt Một',
    CHOT_HAI: 'Chốt Hai',
    CHOT_BA: 'Chốt Ba',
    CHOT_BON: 'Chốt Bốn',
    CHOT_NAM: 'Chốt Năm',
}